name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-amd64:
    runs-on: 
    - self-hosted
    - X64
    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          file: dockerfiles/tbd-racer-develop.dockerfile
          cache-from: type=registry,ref=coalman321/tbd-racer-develop:latest-amd64
          cache-to: type=inline
          tags: |
            coalman321/tbd-racer-develop:latest-amd64
            coalman321/tbd-racer-develop:${{steps.vars.outputs.sha_short}}-amd64

  build-arm64:
    runs-on: 
    - self-hosted
    - ARM64
    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: true
          file: dockerfiles/tbd-racer-develop.dockerfile
          cache-from: type=registry,ref=coalman321/tbd-racer-develop:latest-arm64
          cache-to: type=inline
          tags: |
            coalman321/tbd-racer-develop:latest-arm64
            coalman321/tbd-racer-develop:${{steps.vars.outputs.sha_short}}-arm64
          

